--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/2/2026 11:21:28 AM
-- Server version: 5.7.14
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE barakai;

--
-- Drop table `atsiliepimai`
--
DROP TABLE IF EXISTS atsiliepimai;

--
-- Drop table `ivertinimai`
--
DROP TABLE IF EXISTS ivertinimai;

--
-- Drop table `kambarys`
--
DROP TABLE IF EXISTS kambarys;

--
-- Drop table `dydis`
--
DROP TABLE IF EXISTS dydis;

--
-- Drop table `institucija`
--
DROP TABLE IF EXISTS institucija;

--
-- Drop table `institucijos pavadinimas`
--
DROP TABLE IF EXISTS `institucijos pavadinimas`;

--
-- Drop table `kaina`
--
DROP TABLE IF EXISTS kaina;

--
-- Drop table `valiuta`
--
DROP TABLE IF EXISTS valiuta;

--
-- Drop table `uzimtumas`
--
DROP TABLE IF EXISTS uzimtumas;

--
-- Drop table `asmuo`
--
DROP TABLE IF EXISTS asmuo;

--
-- Drop table `pavarde`
--
DROP TABLE IF EXISTS pavarde;

--
-- Drop table `vardas`
--
DROP TABLE IF EXISTS vardas;

--
-- Drop table `adresas`
--
DROP TABLE IF EXISTS adresas;

--
-- Drop table `gatve`
--
DROP TABLE IF EXISTS gatve;

--
-- Drop table `miestas`
--
DROP TABLE IF EXISTS miestas;

--
-- Drop table `namo nr`
--
DROP TABLE IF EXISTS `namo nr`;

--
-- Drop table `pasto kodas`
--
DROP TABLE IF EXISTS `pasto kodas`;

--
-- Drop table `rajonas`
--
DROP TABLE IF EXISTS rajonas;

--
-- Drop table `kontaktai`
--
DROP TABLE IF EXISTS kontaktai;

--
-- Drop table `el pastas`
--
DROP TABLE IF EXISTS `el pastas`;

--
-- Drop table `el pavadinmas`
--
DROP TABLE IF EXISTS `el pavadinmas`;

--
-- Drop table `telefonas`
--
DROP TABLE IF EXISTS telefonas;

--
-- Drop table `numeris`
--
DROP TABLE IF EXISTS numeris;

--
-- Drop table `salies kodas`
--
DROP TABLE IF EXISTS `salies kodas`;

--
-- Drop table `el domain`
--
DROP TABLE IF EXISTS `el domain`;

--
-- Drop table `country`
--
DROP TABLE IF EXISTS country;

--
-- Set default database
--
USE barakai;

--
-- Create table `country`
--
CREATE TABLE country (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  `salies kodas` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `el domain`
--
CREATE TABLE `el domain` (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  domain VARCHAR(255) DEFAULT NULL,
  `FK salis` INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE `el domain` 
  ADD CONSTRAINT `FK_el domain_country_ID` FOREIGN KEY (`FK salis`)
    REFERENCES country(ID);

--
-- Create table `salies kodas`
--
CREATE TABLE `salies kodas` (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  kodas VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `numeris`
--
CREATE TABLE numeris (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  numeris INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `telefonas`
--
CREATE TABLE telefonas (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  `FK kodas` INT(11) DEFAULT NULL,
  `FK numeris` INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE telefonas 
  ADD CONSTRAINT FK_telefonas_numeris_ID FOREIGN KEY (`FK numeris`)
    REFERENCES numeris(ID);

--
-- Create foreign key
--
ALTER TABLE telefonas 
  ADD CONSTRAINT `FK_telefonas_salies kodas_ID` FOREIGN KEY (`FK kodas`)
    REFERENCES `salies kodas`(ID);

--
-- Create table `el pavadinmas`
--
CREATE TABLE `el pavadinmas` (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  pava VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `el pastas`
--
CREATE TABLE `el pastas` (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  `FK pavadinimas` INT(11) DEFAULT NULL,
  `FK domain` INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE `el pastas` 
  ADD CONSTRAINT `FK_el pastas_el domain_ID` FOREIGN KEY (`FK domain`)
    REFERENCES `el domain`(ID);

--
-- Create foreign key
--
ALTER TABLE `el pastas` 
  ADD CONSTRAINT `FK_el pastas_el pavadinmas_ID` FOREIGN KEY (`FK pavadinimas`)
    REFERENCES `el pavadinmas`(ID);

--
-- Create table `kontaktai`
--
CREATE TABLE kontaktai (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  `FK pastas` INT(11) DEFAULT NULL,
  `FK telefonas` INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE kontaktai 
  ADD CONSTRAINT `FK_kontaktai_el pastas_ID` FOREIGN KEY (`FK pastas`)
    REFERENCES `el pastas`(ID);

--
-- Create foreign key
--
ALTER TABLE kontaktai 
  ADD CONSTRAINT FK_kontaktai_telefonas_ID FOREIGN KEY (`FK telefonas`)
    REFERENCES telefonas(ID);

--
-- Create table `rajonas`
--
CREATE TABLE rajonas (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Pavadinimas VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 41,
AVG_ROW_LENGTH = 409,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `pasto kodas`
--
CREATE TABLE `pasto kodas` (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Kodas INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `namo nr`
--
CREATE TABLE `namo nr` (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Numeris VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 52,
AVG_ROW_LENGTH = 321,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `miestas`
--
CREATE TABLE miestas (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Pavadinimas VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 12,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `gatve`
--
CREATE TABLE gatve (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Pavadinimas VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 44,
AVG_ROW_LENGTH = 381,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `adresas`
--
CREATE TABLE adresas (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  `FK Miestas` INT(11) DEFAULT NULL,
  `FK Rajonas` INT(11) DEFAULT NULL,
  `FK Gatve` INT(11) DEFAULT NULL,
  `FK Namo nr` INT(11) DEFAULT NULL,
  `FK Pasto kodas` INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE adresas 
  ADD CONSTRAINT FK_adresas_gatve_ID FOREIGN KEY (`FK Gatve`)
    REFERENCES gatve(ID);

--
-- Create foreign key
--
ALTER TABLE adresas 
  ADD CONSTRAINT FK_adresas_miestas_ID FOREIGN KEY (`FK Miestas`)
    REFERENCES miestas(ID);

--
-- Create foreign key
--
ALTER TABLE adresas 
  ADD CONSTRAINT `FK_adresas_namo nr_ID` FOREIGN KEY (`FK Namo nr`)
    REFERENCES `namo nr`(ID);

--
-- Create foreign key
--
ALTER TABLE adresas 
  ADD CONSTRAINT `FK_adresas_pasto kodas_ID` FOREIGN KEY (`FK Pasto kodas`)
    REFERENCES `pasto kodas`(ID);

--
-- Create foreign key
--
ALTER TABLE adresas 
  ADD CONSTRAINT FK_adresas_rajonas_ID FOREIGN KEY (`FK Rajonas`)
    REFERENCES rajonas(ID);

--
-- Create table `vardas`
--
CREATE TABLE vardas (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Vardas VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `pavarde`
--
CREATE TABLE pavarde (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Pavarde VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 51,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `asmuo`
--
CREATE TABLE asmuo (
  `Asmens Kodas ID` BIGINT(20) NOT NULL,
  `FK Vardas` INT(11) DEFAULT NULL,
  `FK Pavarde` INT(11) DEFAULT NULL,
  `FK Kontaktai` INT(11) DEFAULT NULL,
  `FK Adresas` INT(11) DEFAULT NULL,
  PRIMARY KEY (`Asmens Kodas ID`)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 327,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE asmuo 
  ADD CONSTRAINT FK_asmuo_adresas_ID FOREIGN KEY (`FK Adresas`)
    REFERENCES adresas(ID);

--
-- Create foreign key
--
ALTER TABLE asmuo 
  ADD CONSTRAINT FK_asmuo_kontaktai_ID FOREIGN KEY (`FK Kontaktai`)
    REFERENCES kontaktai(ID);

--
-- Create foreign key
--
ALTER TABLE asmuo 
  ADD CONSTRAINT FK_asmuo_pavarde_ID FOREIGN KEY (`FK Pavarde`)
    REFERENCES pavarde(ID);

--
-- Create foreign key
--
ALTER TABLE asmuo 
  ADD CONSTRAINT FK_asmuo_vardas_ID FOREIGN KEY (`FK Vardas`)
    REFERENCES vardas(ID);

--
-- Create table `uzimtumas`
--
CREATE TABLE uzimtumas (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  `FK Gyventojai` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE uzimtumas 
  ADD CONSTRAINT `FK_uzimtumas_asmuo_Asmens Kodas ID` FOREIGN KEY (`FK Gyventojai`)
    REFERENCES asmuo(`Asmens Kodas ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `valiuta`
--
CREATE TABLE valiuta (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Valiuta VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `kaina`
--
CREATE TABLE kaina (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Kiek INT(11) DEFAULT NULL,
  `FK Valiuta` INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE kaina 
  ADD CONSTRAINT FK_kaina_valiuta_ID FOREIGN KEY (`FK Valiuta`)
    REFERENCES valiuta(ID);

--
-- Create table `institucijos pavadinimas`
--
CREATE TABLE `institucijos pavadinimas` (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  pavadinimas VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `institucija`
--
CREATE TABLE institucija (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  `FK Pavadinimas` INT(11) DEFAULT NULL,
  `FK Adresas` INT(11) DEFAULT NULL,
  `FK Kontaktai` INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE institucija 
  ADD CONSTRAINT FK_institucija_adresas_ID FOREIGN KEY (`FK Adresas`)
    REFERENCES adresas(ID);

--
-- Create foreign key
--
ALTER TABLE institucija 
  ADD CONSTRAINT `FK_institucija_institucijos pavadinimas_ID` FOREIGN KEY (`FK Pavadinimas`)
    REFERENCES `institucijos pavadinimas`(ID);

--
-- Create foreign key
--
ALTER TABLE institucija 
  ADD CONSTRAINT FK_institucija_kontaktai_ID FOREIGN KEY (`FK Kontaktai`)
    REFERENCES kontaktai(ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `dydis`
--
CREATE TABLE dydis (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Dydis INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `kambarys`
--
CREATE TABLE kambarys (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  `FK Dydis` INT(11) DEFAULT NULL,
  `FK Kaina` INT(11) DEFAULT NULL,
  `FK Uzimtumas` INT(11) DEFAULT NULL,
  `FK Adresas` INT(11) DEFAULT NULL,
  `FK Nuomininkas` INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE kambarys 
  ADD CONSTRAINT FK_kambarys_adresas_ID FOREIGN KEY (`FK Adresas`)
    REFERENCES adresas(ID);

--
-- Create foreign key
--
ALTER TABLE kambarys 
  ADD CONSTRAINT FK_kambarys_dydis_ID FOREIGN KEY (`FK Dydis`)
    REFERENCES dydis(ID);

--
-- Create foreign key
--
ALTER TABLE kambarys 
  ADD CONSTRAINT FK_kambarys_institucija_ID FOREIGN KEY (`FK Nuomininkas`)
    REFERENCES institucija(ID);

--
-- Create foreign key
--
ALTER TABLE kambarys 
  ADD CONSTRAINT FK_kambarys_kaina_ID FOREIGN KEY (`FK Kaina`)
    REFERENCES kaina(ID);

--
-- Create foreign key
--
ALTER TABLE kambarys 
  ADD CONSTRAINT FK_kambarys_uzimtumas_ID FOREIGN KEY (`FK Uzimtumas`)
    REFERENCES uzimtumas(ID);

--
-- Create table `ivertinimai`
--
CREATE TABLE ivertinimai (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  `FK Kambarys` INT(11) DEFAULT NULL,
  `FK Ivertines asmuo` BIGINT(20) DEFAULT NULL,
  Ivertinimas VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE ivertinimai 
  ADD CONSTRAINT `FK_ivertinimai_asmuo_Asmens Kodas ID` FOREIGN KEY (`FK Ivertines asmuo`)
    REFERENCES asmuo(`Asmens Kodas ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE ivertinimai 
  ADD CONSTRAINT FK_ivertinimai_kambarys_ID FOREIGN KEY (`FK Kambarys`)
    REFERENCES kambarys(ID);

--
-- Create table `atsiliepimai`
--
CREATE TABLE atsiliepimai (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  `FK Kambarys` INT(11) DEFAULT NULL,
  `FK Komentves Asmuo` BIGINT(20) DEFAULT NULL,
  Komentaras VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE atsiliepimai 
  ADD CONSTRAINT `FK_atsiliepimai_asmuo_Asmens Kodas ID` FOREIGN KEY (`FK Komentves Asmuo`)
    REFERENCES asmuo(`Asmens Kodas ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE atsiliepimai 
  ADD CONSTRAINT FK_atsiliepimai_kambarys_ID FOREIGN KEY (`FK Kambarys`)
    REFERENCES kambarys(ID);

-- 
-- Dumping data for table country
--
INSERT INTO country VALUES
(1, '.lt');

-- 
-- Dumping data for table `salies kodas`
--
INSERT INTO `salies kodas` VALUES
(1, '370');

-- 
-- Dumping data for table numeris
--
INSERT INTO numeris VALUES
(1, 60000101),
(2, 60000102),
(3, 60000103),
(4, 60000104),
(5, 60000105),
(6, 60000106),
(7, 60000107),
(8, 60000108),
(9, 60000109),
(10, 60000110),
(11, 60000111),
(12, 60000112),
(13, 60000113),
(14, 60000114),
(15, 60000115),
(16, 60000116),
(17, 60000117),
(18, 60000118),
(19, 60000119),
(20, 60000120),
(21, 60000121),
(22, 60000122),
(23, 60000123),
(24, 60000124),
(25, 60000125),
(26, 60000126),
(27, 60000127),
(28, 60000128),
(29, 60000129),
(30, 60000130),
(31, 60000131),
(32, 60000132),
(33, 60000133),
(34, 60000134),
(35, 60000135),
(36, 60000136),
(37, 60000137),
(38, 60000138),
(39, 60000139),
(40, 60000140),
(41, 60000141),
(42, 60000142),
(43, 60000143),
(44, 60000144),
(45, 60000145),
(46, 60000146),
(47, 60000147),
(48, 60000148),
(49, 60000149),
(50, 60000150);

-- 
-- Dumping data for table `el pavadinmas`
--
INSERT INTO `el pavadinmas` VALUES
(1, 'jonas.k'),
(2, 'mantas.p'),
(3, 'lukas.j'),
(4, 'dovydas.v'),
(5, 'karolis.u'),
(6, 'tomas.p'),
(7, 'paulius.m'),
(8, 'rokas.b'),
(9, 'justas.s'),
(10, 'arnas.k'),
(11, 'egle.k'),
(12, 'aiste.p'),
(13, 'gabija.j'),
(14, 'ieva.v'),
(15, 'agne.u'),
(16, 'ugne.p'),
(17, 'monika.m'),
(18, 'karolina.b'),
(19, 'greta.s'),
(20, 'emilija.k'),
(21, 'simonas.b'),
(22, 'edgaras.z'),
(23, 'vytautas.s'),
(24, 'mindaugas.k'),
(25, 'giedrius.d'),
(26, 'ruta.z'),
(27, 'viktorija.b'),
(28, 'laura.k'),
(29, 'sandra.m'),
(30, 'jolanta.s'),
(31, 'andrius.k'),
(32, 'martynas.s'),
(33, 'saulius.d'),
(34, 'ernestas.v'),
(35, 'deividas.k'),
(36, 'kristina.b'),
(37, 'inga.s'),
(38, 'aurelija.k'),
(39, 'neringa.v'),
(40, 'jurgita.m'),
(41, 'arvydas.k'),
(42, 'tautvydas.s'),
(43, 'dominykas.d'),
(44, 'edvinas.v'),
(45, 'gintaras.k'),
(46, 'aldona.b'),
(47, 'birute.s'),
(48, 'janina.k'),
(49, 'ona.m'),
(50, 'vanda.s');

-- 
-- Dumping data for table `el domain`
--
INSERT INTO `el domain` VALUES
(1, '@gmail', 1),
(2, '@inbox', 1),
(3, '@takas', 1),
(4, '@one', 1),
(5, '@pastas', 1);

-- 
-- Dumping data for table telefonas
--
INSERT INTO telefonas VALUES
(1, 1, 1),
(2, 1, 2),
(3, 1, 3),
(4, 1, 4),
(5, 1, 5),
(6, 1, 6),
(7, 1, 7),
(8, 1, 8),
(9, 1, 9),
(10, 1, 10),
(11, 1, 11),
(12, 1, 12),
(13, 1, 13),
(14, 1, 14),
(15, 1, 15),
(16, 1, 16),
(17, 1, 17),
(18, 1, 18),
(19, 1, 19),
(20, 1, 20),
(21, 1, 21),
(22, 1, 22),
(23, 1, 23),
(24, 1, 24),
(25, 1, 25),
(26, 1, 26),
(27, 1, 27),
(28, 1, 28),
(29, 1, 29),
(30, 1, 30),
(31, 1, 31),
(32, 1, 32),
(33, 1, 33),
(34, 1, 34),
(35, 1, 35),
(36, 1, 36),
(37, 1, 37),
(38, 1, 38),
(39, 1, 39),
(40, 1, 40),
(41, 1, 41),
(42, 1, 42),
(43, 1, 43),
(44, 1, 44),
(45, 1, 45),
(46, 1, 46),
(47, 1, 47),
(48, 1, 48),
(49, 1, 49),
(50, 1, 50);

-- 
-- Dumping data for table `el pastas`
--
INSERT INTO `el pastas` VALUES
(1, 1, 1),
(2, 2, 1),
(3, 3, 1),
(4, 4, 1),
(5, 5, 1),
(6, 6, 1),
(7, 7, 1),
(8, 8, 1),
(9, 9, 1),
(10, 10, 1),
(11, 11, 2),
(12, 12, 2),
(13, 13, 2),
(14, 14, 2),
(15, 15, 2),
(16, 16, 2),
(17, 17, 2),
(18, 18, 2),
(19, 19, 2),
(20, 20, 2),
(21, 21, 3),
(22, 22, 3),
(23, 23, 3),
(24, 24, 3),
(25, 25, 3),
(26, 26, 3),
(27, 27, 3),
(28, 28, 3),
(29, 29, 3),
(30, 30, 3),
(31, 31, 4),
(32, 32, 4),
(33, 33, 4),
(34, 34, 4),
(35, 35, 4),
(36, 36, 4),
(37, 37, 4),
(38, 38, 4),
(39, 39, 4),
(40, 40, 4),
(41, 41, 5),
(42, 42, 5),
(43, 43, 5),
(44, 44, 5),
(45, 45, 5),
(46, 46, 5),
(47, 47, 5),
(48, 48, 5),
(49, 49, 5),
(50, 50, 5);

-- 
-- Dumping data for table rajonas
--
INSERT INTO rajonas VALUES
(1, 'Senamiestis'),
(2, 'Antakalnis'),
(3, 'Rasos'),
(4, 'Fabijonišk?s'),
(5, 'Verkiai'),
(6, 'Naujininkai'),
(7, 'Naujoji Vilnia'),
(8, 'Šnipišk?s'),
(9, 'Centras'),
(10, 'Žaliakalnis'),
(11, 'Šilainiai'),
(12, 'Dainava'),
(13, 'Panemune'),
(14, 'Petrašiunai'),
(15, 'Aleksotas'),
(16, 'Senamiestis'),
(17, 'Žvejybos uostas'),
(18, 'Debrecenas'),
(19, 'Bandužiai'),
(20, 'Smelte'),
(21, 'Pempininkai'),
(22, 'Gubernija'),
(23, 'Lieporiai'),
(24, 'Dainiai'),
(25, 'Medelynas'),
(26, 'Kniaudiškiai'),
(27, 'Rožynas'),
(28, 'Stetiškiai'),
(29, 'Savitiškiai'),
(30, 'Putinai'),
(31, 'Vidzgiris'),
(32, 'Naujamiestis'),
(33, 'Mokolai'),
(34, 'Tarpuciai'),
(35, 'Aukštakalnis'),
(36, 'Dauniškis'),
(37, 'Karalius Mindaugas'),
(38, 'Žemaite'),
(39, 'Žalgiriai'),
(40, 'Ventos');

-- 
-- Dumping data for table `pasto kodas`
--
INSERT INTO `pasto kodas` VALUES
(1, 1100),
(2, 10257),
(3, 10222),
(4, 10223),
(5, 7117),
(6, 10221),
(7, 10224),
(8, 8414),
(9, 2121),
(10, 10233),
(11, 11115),
(12, 9301),
(13, 7118),
(14, 10312),
(15, 10313),
(16, 10308),
(17, 44280),
(18, 44149),
(19, 47240),
(20, 92294),
(21, 94144),
(22, 95251),
(23, 76285),
(24, 77157),
(25, 78366),
(26, 35199),
(27, 37166),
(28, 37355),
(29, 62114),
(30, 63308),
(31, 63267),
(32, 68182),
(33, 68252),
(34, 68191),
(35, 28141),
(36, 28209),
(37, 28199),
(38, 87121),
(39, 87315),
(40, 87234),
(41, 72114),
(42, 72336),
(43, 72116),
(44, 89145),
(45, 89239),
(46, 89147),
(47, 49438),
(48, 94246),
(49, 76289),
(50, 37164);

-- 
-- Dumping data for table `namo nr`
--
INSERT INTO `namo nr` VALUES
(1, '51'),
(2, '39'),
(3, '37'),
(4, '4'),
(5, '59'),
(6, '33'),
(7, '35'),
(8, '45'),
(9, '14'),
(10, '61'),
(11, '47'),
(12, '3'),
(13, '81'),
(14, '63'),
(15, '52'),
(16, '56'),
(17, '20'),
(18, '1'),
(19, '3'),
(20, '5'),
(21, '7'),
(22, '9'),
(23, '11'),
(24, '13'),
(25, '15'),
(26, '17'),
(27, '19'),
(28, '21'),
(29, '23'),
(30, '25'),
(31, '27'),
(32, '29'),
(33, '31'),
(34, '33'),
(35, '35'),
(36, '37'),
(37, '39'),
(38, '41'),
(39, '43'),
(40, '45'),
(41, '47'),
(42, '49'),
(43, '51'),
(44, '53'),
(45, '55'),
(46, '57'),
(47, '59'),
(48, '61'),
(49, '63'),
(50, '65'),
(51, '67');

-- 
-- Dumping data for table miestas
--
INSERT INTO miestas VALUES
(1, 'Vilnius'),
(2, 'Kaunas'),
(3, 'Klaipeda'),
(4, 'Šiauliai'),
(5, 'Panevežys'),
(6, 'Alytus'),
(7, 'Marijampole'),
(8, 'Utena'),
(9, 'Telšiai'),
(10, 'Taurage'),
(11, 'Mažeikiai');

-- 
-- Dumping data for table gatve
--
INSERT INTO gatve VALUES
(1, 'Oland? g.'),
(2, 'Saul?tekio al.'),
(3, 'Didlaukio g.'),
(4, 'Verki? g.'),
(5, 'Šaltkalvi? g.'),
(6, 'Student? g.'),
(7, 'Statybinink? g.'),
(8, 'Giedrai?i? g.'),
(9, 'Antakalnio g.'),
(10, 'P. Vileišio g.'),
(11, 'Laisves al.'),
(12, 'Savanoriu pr.'),
(13, 'Taikos pr.'),
(14, 'H. Manto g.'),
(15, 'Tiltu g.'),
(16, 'Tilžes g.'),
(17, 'Aušros al.'),
(18, 'Vytauto g.'),
(19, 'J. Basanaviciaus g.'),
(20, 'Žemaites g.'),
(21, 'Kestucio g.'),
(22, 'Birutes g.'),
(23, 'Vilties g.'),
(24, 'Parko g.'),
(25, 'Ežero g.'),
(26, 'Pievu g.'),
(27, 'Ažuolu g.'),
(28, 'Pušu g.'),
(29, 'Beržu g.'),
(30, 'Geliu g.'),
(31, 'Rasos g.'),
(32, 'Saules g.'),
(33, 'Debesu g.'),
(34, 'Vejo g.'),
(35, 'Smelio g.'),
(36, 'Juros g.'),
(37, 'Mindaugo g.'),
(38, 'Šermukšniu g.'),
(39, 'Ažuolyno g.'),
(40, 'Dariaus ir Gireno g.'),
(41, 'Klaipedos g.'),
(42, 'J. Janonio g.'),
(43, 'Respublikos g.');

-- 
-- Dumping data for table vardas
--
INSERT INTO vardas VALUES
(1, 'Jonas'),
(2, 'Mantas'),
(3, 'Lukas'),
(4, 'Dovydas'),
(5, 'Karolis'),
(6, 'Tomas'),
(7, 'Paulius'),
(8, 'Rokas'),
(9, 'Justas'),
(10, 'Arnas'),
(11, 'Egle'),
(12, 'Aiste'),
(13, 'Gabija'),
(14, 'Ieva'),
(15, 'Agne'),
(16, 'Ugne'),
(17, 'Monika'),
(18, 'Karolina'),
(19, 'Greta'),
(20, 'Emilija'),
(21, 'Simonas'),
(22, 'Edgaras'),
(23, 'Vytautas'),
(24, 'Mindaugas'),
(25, 'Giedrius'),
(26, 'Ruta'),
(27, 'Viktorija'),
(28, 'Laura'),
(29, 'Sandra'),
(30, 'Jolanta'),
(31, 'Andrius'),
(32, 'Martynas'),
(33, 'Saulius'),
(34, 'Ernestas'),
(35, 'Deividas'),
(36, 'Kristina'),
(37, 'Inga'),
(38, 'Aurelija'),
(39, 'Neringa'),
(40, 'Jurgita'),
(41, 'Arvydas'),
(42, 'Tautvydas'),
(43, 'Dominykas'),
(44, 'Edvinas'),
(45, 'Gintaras'),
(46, 'Aldona'),
(47, 'Birute'),
(48, 'Janina'),
(49, 'Ona'),
(50, 'Vanda');

-- 
-- Dumping data for table pavarde
--
INSERT INTO pavarde VALUES
(1, 'Kazlauskas'),
(2, 'Petrauskas'),
(3, 'Jankauskas'),
(4, 'Vasiliauskas'),
(5, 'Urbonas'),
(6, 'Paulauskas'),
(7, 'Misevicius'),
(8, 'Bieliauskas'),
(9, 'Stankevicius'),
(10, 'Kavaliauskas'),
(11, 'Kazlauskiene'),
(12, 'Petrauskiene'),
(13, 'Jankauskiene'),
(14, 'Vasiliauskiene'),
(15, 'Urboniene'),
(16, 'Paulauskiene'),
(17, 'Miseviciene'),
(18, 'Bieliauskiene'),
(19, 'Stankeviciene'),
(20, 'Kavaliauskiene'),
(21, 'Butkus'),
(22, 'Balciunas'),
(23, 'Zabiela'),
(24, 'Šimkus'),
(25, 'Kairys'),
(26, 'Žukauskaite'),
(27, 'Bartaškaite'),
(28, 'Kvietkute'),
(29, 'Milašaite'),
(30, 'Šimkute'),
(31, 'Mockus'),
(32, 'Gricius'),
(33, 'Kundrotas'),
(34, 'Sakalauskas'),
(35, 'Dambrauskas'),
(36, 'Kairiene'),
(37, 'Žukauskiene'),
(38, 'Bartaškiene'),
(39, 'Kvietkiene'),
(40, 'Milašiene'),
(41, 'Šimkunas'),
(42, 'Kundrotas'),
(43, 'Sakalauskas'),
(44, 'Dambrauskas'),
(45, 'Gricius'),
(46, 'Butkiene'),
(47, 'Balciuniene'),
(48, 'Zabieliene'),
(49, 'Kairiene'),
(50, 'Mockiene');

-- 
-- Dumping data for table kontaktai
--
INSERT INTO kontaktai VALUES
(1, 1, 1),
(2, 2, 2),
(3, 3, 3),
(4, 4, 4),
(5, 5, 5),
(6, 6, 6),
(7, 7, 7),
(8, 8, 8),
(9, 9, 9),
(10, 10, 10),
(11, 11, 11),
(12, 12, 12),
(13, 13, 13),
(14, 14, 14),
(15, 15, 15),
(16, 16, 16),
(17, 17, 17),
(18, 18, 18),
(19, 19, 19),
(20, 20, 20),
(21, 21, 21),
(22, 22, 22),
(23, 23, 23),
(24, 24, 24),
(25, 25, 25),
(26, 26, 26),
(27, 27, 27),
(28, 28, 28),
(29, 29, 29),
(30, 30, 30),
(31, 31, 31),
(32, 32, 32),
(33, 33, 33),
(34, 34, 34),
(35, 35, 35),
(36, 36, 36),
(37, 37, 37),
(38, 38, 38),
(39, 39, 39),
(40, 40, 40),
(41, 41, 41),
(42, 42, 42),
(43, 43, 43),
(44, 44, 44),
(45, 45, 45),
(46, 46, 46),
(47, 47, 47),
(48, 48, 48),
(49, 49, 49),
(50, 50, 50);

-- 
-- Dumping data for table adresas
--
INSERT INTO adresas VALUES
(1, 1, 1, 1, 1, 1),
(2, 1, 2, 2, 2, 2),
(3, 1, 2, 2, 3, 3),
(4, 1, 2, 2, 4, 4),
(5, 1, 4, 3, 5, 5),
(6, 1, 2, 2, 6, 6),
(7, 1, 2, 2, 7, 7),
(8, 1, 5, 4, 8, 8),
(9, 1, 6, 5, 9, 9),
(10, 1, 2, 6, 11, 10),
(11, 1, 7, 7, 12, 11),
(12, 1, 8, 8, 13, 12),
(13, 1, 4, 3, 14, 13),
(14, 1, 2, 9, 15, 14),
(15, 1, 2, 9, 16, 15),
(16, 1, 2, 10, 17, 16),
(17, 2, 9, 11, 18, 17),
(18, 2, 10, 12, 19, 18),
(19, 2, 11, 13, 20, 19),
(20, 3, 16, 14, 21, 20),
(21, 3, 18, 15, 22, 21),
(22, 3, 19, 16, 23, 22),
(23, 4, 16, 17, 24, 23),
(24, 4, 22, 18, 25, 24),
(25, 4, 23, 19, 26, 25),
(26, 5, 16, 20, 27, 26),
(27, 5, 26, 21, 28, 27),
(28, 5, 27, 22, 29, 28),
(29, 6, 16, 23, 30, 29),
(30, 6, 30, 24, 31, 30),
(31, 6, 31, 25, 32, 31),
(32, 7, 16, 26, 33, 32),
(33, 7, 32, 27, 34, 33),
(34, 7, 33, 28, 35, 34),
(35, 8, 16, 29, 36, 35),
(36, 8, 35, 30, 37, 36),
(37, 8, 36, 31, 38, 37),
(38, 9, 16, 32, 39, 38),
(39, 9, 37, 33, 40, 39),
(40, 9, 38, 34, 41, 40),
(41, 10, 16, 35, 42, 41),
(42, 10, 39, 36, 43, 42),
(43, 10, 16, 37, 44, 43),
(44, 11, 16, 38, 45, 44),
(45, 11, 40, 39, 46, 45),
(46, 11, 16, 40, 47, 46),
(47, 2, 12, 41, 48, 47),
(48, 3, 21, 42, 49, 48),
(49, 4, 24, 43, 50, 49),
(50, 5, 28, 11, 51, 50);

-- 
-- Dumping data for table asmuo
--
INSERT INTO asmuo VALUES
(39901011234, 1, 1, 1, 1),
(39902051257, 2, 2, 2, 2),
(39903141211, 3, 3, 3, 3),
(39904181299, 4, 4, 4, 4),
(39905251245, 5, 5, 5, 5),
(39911011234, 21, 21, 21, 21),
(39912051257, 22, 22, 22, 22),
(39913141211, 23, 23, 23, 23),
(39914181299, 24, 24, 24, 24),
(39915251245, 25, 25, 25, 25),
(39921011234, 41, 41, 41, 41),
(39922051257, 42, 42, 42, 42),
(39923141211, 43, 43, 43, 43),
(39924181299, 44, 44, 44, 44),
(39925251245, 45, 45, 45, 45),
(49906181234, 6, 6, 6, 6),
(49907151257, 7, 7, 7, 7),
(49908121211, 8, 8, 8, 8),
(49909181299, 9, 9, 9, 9),
(49910151245, 10, 10, 10, 10),
(49916181234, 26, 26, 26, 26),
(49917151257, 27, 27, 27, 27),
(49918121211, 28, 28, 28, 28),
(49919181299, 29, 29, 29, 29),
(49920151245, 30, 30, 30, 30),
(49926181234, 46, 46, 46, 46),
(49927151257, 47, 47, 47, 47),
(49928121211, 48, 48, 48, 48),
(49929181299, 49, 49, 49, 49),
(49930151245, 50, 50, 50, 50),
(60101011234, 11, 11, 11, 11),
(60102051257, 12, 12, 12, 12),
(60103141211, 13, 13, 13, 13),
(60104181299, 14, 14, 14, 14),
(60105251245, 15, 15, 15, 15),
(60111011234, 31, 31, 31, 31),
(60112051257, 32, 32, 32, 32),
(60113141211, 33, 33, 33, 33),
(60114181299, 34, 34, 34, 34),
(60115251245, 35, 35, 35, 35),
(60206181234, 16, 16, 16, 16),
(60207151257, 17, 17, 17, 17),
(60208121211, 18, 18, 18, 18),
(60209181299, 19, 19, 19, 19),
(60210151245, 20, 20, 20, 20),
(60216181234, 36, 36, 36, 36),
(60217151257, 37, 37, 37, 37),
(60218121211, 38, 38, 38, 38),
(60219181299, 39, 39, 39, 39),
(60220151245, 40, 40, 40, 40);

-- 
-- Dumping data for table valiuta
--
-- Table barakai.valiuta does not contain any data (it is empty)

-- 
-- Dumping data for table `institucijos pavadinimas`
--
-- Table barakai.`institucijos pavadinimas` does not contain any data (it is empty)

-- 
-- Dumping data for table uzimtumas
--
-- Table barakai.uzimtumas does not contain any data (it is empty)

-- 
-- Dumping data for table kaina
--
-- Table barakai.kaina does not contain any data (it is empty)

-- 
-- Dumping data for table institucija
--
-- Table barakai.institucija does not contain any data (it is empty)

-- 
-- Dumping data for table dydis
--
-- Table barakai.dydis does not contain any data (it is empty)

-- 
-- Dumping data for table kambarys
--
-- Table barakai.kambarys does not contain any data (it is empty)

-- 
-- Dumping data for table ivertinimai
--
-- Table barakai.ivertinimai does not contain any data (it is empty)

-- 
-- Dumping data for table atsiliepimai
--
-- Table barakai.atsiliepimai does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;