--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2025.3.107.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 4/1/2026 1:39:37 PM
-- Server version: 8.0.45
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE supaprastintas;

--
-- Drop table `svecias`
--
DROP TABLE IF EXISTS svecias;

--
-- Drop table `atsiliepimai`
--
DROP TABLE IF EXISTS atsiliepimai;

--
-- Drop table `pageidavimai`
--
DROP TABLE IF EXISTS pageidavimai;

--
-- Drop table `gyventojas`
--
DROP TABLE IF EXISTS gyventojas;

--
-- Drop table `kambarys`
--
DROP TABLE IF EXISTS kambarys;

--
-- Drop table `barakas`
--
DROP TABLE IF EXISTS barakas;

--
-- Set default database
--
USE supaprastintas;

--
-- Create table `barakas`
--
CREATE TABLE barakas (
  id int NOT NULL AUTO_INCREMENT,
  Adresas varchar(255) NOT NULL,
  Institucija varchar(255) NOT NULL,
  Telefonas varchar(255) DEFAULT NULL,
  Pastas varchar(255) DEFAULT NULL,
  `Kainos studentams` varchar(255) DEFAULT NULL,
  `Kainos sveciams` varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `kambarys`
--
CREATE TABLE kambarys (
  id int NOT NULL AUTO_INCREMENT,
  `Kambario NR` int NOT NULL,
  `Vietu kiekis` int NOT NULL,
  `Priklauso barakui` int NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE kambarys
ADD CONSTRAINT FK_kambarys_barakas_id FOREIGN KEY (`Priklauso barakui`)
REFERENCES barakas (id);

--
-- Create table `gyventojas`
--
CREATE TABLE gyventojas (
  id int NOT NULL AUTO_INCREMENT,
  Vardas varchar(255) NOT NULL,
  Pavarde varchar(255) NOT NULL,
  Telefonas varchar(255) DEFAULT NULL,
  Pastas varchar(255) DEFAULT NULL,
  Apsigyvenes int DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE gyventojas
ADD CONSTRAINT FK_gyventojas_kambarys_id FOREIGN KEY (Apsigyvenes)
REFERENCES kambarys (id);

--
-- Create table `pageidavimai`
--
CREATE TABLE pageidavimai (
  id int NOT NULL AUTO_INCREMENT,
  Kambariui int DEFAULT NULL,
  Asmuo int DEFAULT NULL,
  Pageidauja varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE pageidavimai
ADD CONSTRAINT FK_pageidavimai_gyventojas_id FOREIGN KEY (Asmuo)
REFERENCES gyventojas (id);

--
-- Create foreign key
--
ALTER TABLE pageidavimai
ADD CONSTRAINT FK_pageidavimai_kambarys_id FOREIGN KEY (Kambariui)
REFERENCES kambarys (id);

--
-- Create table `atsiliepimai`
--
CREATE TABLE atsiliepimai (
  id int NOT NULL AUTO_INCREMENT,
  `Kas parase` int DEFAULT NULL,
  Kambarys int DEFAULT NULL,
  Barakas int DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE atsiliepimai
ADD CONSTRAINT FK_atsiliepimai_barakas_id FOREIGN KEY (Barakas)
REFERENCES barakas (id);

--
-- Create foreign key
--
ALTER TABLE atsiliepimai
ADD CONSTRAINT FK_atsiliepimai_gyventojas_id FOREIGN KEY (`Kas parase`)
REFERENCES gyventojas (id);

--
-- Create foreign key
--
ALTER TABLE atsiliepimai
ADD CONSTRAINT FK_atsiliepimai_kambarys_id FOREIGN KEY (Kambarys)
REFERENCES kambarys (id);

--
-- Create table `svecias`
--
CREATE TABLE svecias (
  id int NOT NULL AUTO_INCREMENT,
  Vardas varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

-- Table supaprastintas.barakas does not contain any data (it is empty)

-- Table supaprastintas.kambarys does not contain any data (it is empty)

-- Table supaprastintas.gyventojas does not contain any data (it is empty)

-- Table supaprastintas.svecias does not contain any data (it is empty)

-- Table supaprastintas.pageidavimai does not contain any data (it is empty)

-- Table supaprastintas.atsiliepimai does not contain any data (it is empty)

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;